import { CaseCard, Label } from "./types";

const T = new Date();

function da(n: number): string {
  const d = new Date(T);
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

export const RECV_COLS = [
  "법무이관",
  "지급명령·소장",
  "강제집행",
  "분할변제 이행중",
  "추심종료",
  "장기추심중",
];

export const DISP_COLS = [
  "법무이관",
  "합의진행중",
  "본안소송",
  "강제집행",
  "종결",
];

export const DEFAULT_LABELS: Label[] = [
  { id: "lb1", name: "조정기일", color: "r" },
  { id: "lb2", name: "압류추심", color: "r" },
  { id: "lb3", name: "지급명령", color: "o" },
  { id: "lb4", name: "가압류", color: "o" },
  { id: "lb5", name: "보정중", color: "r" },
  { id: "lb6", name: "보정", color: "b" },
  { id: "lb7", name: "장기미업데이트", color: "gy" },
  { id: "lb8", name: "이행중", color: "gr" },
  { id: "lb9", name: "완료", color: "gr" },
  { id: "lb10", name: "협의중", color: "g" },
  { id: "lb11", name: "합의중", color: "g" },
  { id: "lb12", name: "소송중", color: "o" },
  { id: "lb13", name: "증거수집", color: "o" },
  { id: "lb14", name: "이관", color: "b" },
  { id: "lb15", name: "집행중", color: "r" },
  { id: "lb16", name: "종결", color: "gr" },
  { id: "lb17", name: "신규", color: "b" },
  { id: "lb18", name: "긴급", color: "r" },
  { id: "lb19", name: "검토필요", color: "g" },
  { id: "lb20", name: "대기", color: "gy" },
];

export const initialRecvData: CaseCard[] = [
  {
    id: "r1",
    name: "맥스인포텍",
    sub: "용역비 청구 조정기일",
    col: "지급명령·소장",
    labels: ["lb1"],
    drv: "https://drive.google.com",
    lu: da(0),
    amt: { orig: 15000000, paid: 0, extra: 0 },
    tl: [
      { dt: "2026.01.15", ti: "법무이관", dc: "내부 검토 후 이관", dn: true },
      {
        dt: "2026.03.27",
        ti: "조정기일",
        dc: "15:00 서울법원조정센터",
        dn: false,
      },
    ],
    fu: [
      { dt: "2026-03-27", ti: "조정기일 참석 확인", dn: false },
      { dt: "2026-04-10", ti: "조정 결과 정리", dn: false },
    ],
  },
  {
    id: "r2",
    name: "이진해",
    sub: "채권압류 국민·하나은행",
    col: "강제집행",
    labels: ["lb2"],
    drv: "https://drive.google.com",
    lu: da(3),
    amt: { orig: 8500000, paid: 0, extra: 0 },
    tl: [
      { dt: "2025.09.01", ti: "법무이관", dc: "이용요금 미납", dn: true },
      {
        dt: "2026.02.25",
        ti: "채권압류 및 추심명령",
        dc: "2개 계좌 압류",
        dn: true,
      },
    ],
    fu: [{ dt: "2026-04-01", ti: "국민은행 압류 결과 확인", dn: false }],
  },
  {
    id: "r3",
    name: "스포칙",
    sub: "지급명령 2026차전42066",
    col: "지급명령·소장",
    labels: ["lb3"],
    drv: "https://drive.google.com",
    lu: da(2),
    amt: { orig: 25410000, paid: 0, extra: 0 },
    tl: [
      {
        dt: "2026.03.16",
        ti: "지급명령 신청",
        dc: "청구금액 25,410,000원",
        dn: true,
      },
    ],
    fu: [],
  },
  {
    id: "r4",
    name: "엘링크",
    sub: "이용요금 미납 가압류",
    col: "법무이관",
    labels: ["lb4"],
    drv: "https://drive.google.com",
    lu: da(1),
    amt: { orig: 5000000, paid: 0, extra: 0 },
    tl: [{ dt: "2026.03.04", ti: "가압류 신청", dn: true }],
    fu: [{ dt: "2026-04-15", ti: "30% 입금 확인", dn: false }],
  },
  {
    id: "r5",
    name: "나노센스",
    sub: "주소보정명령 3차",
    col: "지급명령·소장",
    labels: ["lb5"],
    drv: "https://drive.google.com",
    lu: da(5),
    amt: { orig: 3200000, paid: 0, extra: 0 },
    tl: [
      {
        dt: "2026.03.09",
        ti: "주소보정명령 재접수",
        dc: "1개월 경과",
        dn: true,
      },
    ],
    fu: [{ dt: "2026-04-14", ti: "특별송달 신청", dn: false }],
  },
  {
    id: "r6",
    name: "김일두",
    sub: "부당이득금 보정명령",
    col: "법무이관",
    labels: ["lb6"],
    drv: "https://drive.google.com",
    lu: da(4),
    amt: { orig: 2000000, paid: 0, extra: 0 },
    tl: [
      { dt: "2026.03.12", ti: "보정명령 접수", dn: true },
      { dt: "2026.03.24", ti: "보정서 제출", dc: "완료", dn: true },
    ],
    fu: [{ dt: "2026-04-01", ti: "보정 처리 결과 확인", dn: false }],
  },
  {
    id: "r7",
    name: "최용성",
    sub: "채권압류추심",
    col: "강제집행",
    labels: ["lb7"],
    drv: "https://drive.google.com",
    lu: da(48),
    amt: { orig: 12000000, paid: 0, extra: 0 },
    tl: [{ dt: "2026.01.15", ti: "채권압류 신청", dn: true }],
    fu: [],
  },
  {
    id: "r8",
    name: "모빌리티엔",
    sub: "1차 납부완료 분할변제",
    col: "분할변제 이행중",
    labels: ["lb8"],
    drv: "https://drive.google.com",
    lu: da(6),
    amt: { orig: 32000000, paid: 6400000, extra: 500000 },
    tl: [
      { dt: "2026.02.20", ti: "분할변제 합의", dn: true },
      { dt: "2026.03.10", ti: "1차 20% 납부", dc: "완료", dn: true },
    ],
    fu: [
      { dt: "2026-04-15", ti: "2차 30% 납부 확인", dn: false },
      { dt: "2026-04-30", ti: "잔금 50% 확인", dn: false },
    ],
  },
  {
    id: "r9",
    name: "인베스티",
    sub: "소취 완료",
    col: "추심종료",
    labels: ["lb9"],
    drv: "https://drive.google.com",
    lu: da(10),
    amt: { orig: 8900000, paid: 8900000, extra: 320000 },
    tl: [{ dt: "2026.03.17", ti: "소취 완료", dn: true }],
    fu: [],
  },
];

export const initialDispData: CaseCard[] = [
  {
    id: "d1",
    name: "비쥬웍스·도겐소프트",
    sub: "CRM·EMR 개발 분쟁",
    col: "합의진행중",
    labels: ["lb10"],
    drv: "https://drive.google.com",
    lu: da(7),
    tl: [
      { dt: "2025.09.15", ti: "분쟁 접수", dn: true },
      { dt: "2025.12.10", ti: "법무 검토 완료", dn: true },
    ],
    fu: [{ dt: "2026-04-15", ti: "협의 결과 확인", dn: false }],
  },
  {
    id: "d2",
    name: "웹빌더 돌봄서비스",
    sub: "양소영-이행렬",
    col: "합의진행중",
    labels: ["lb11"],
    drv: "https://drive.google.com",
    lu: da(2),
    tl: [
      { dt: "2026.02.20", ti: "합의 시작", dn: true },
      { dt: "2026.03.10", ti: "1차 납부 완료", dn: true },
    ],
    fu: [
      { dt: "2026-03-31", ti: "2차 20% 입금 확인", dn: false },
      { dt: "2026-04-15", ti: "3차 30% 입금 확인", dn: false },
    ],
  },
  {
    id: "d3",
    name: "시험채점 시스템 구축",
    sub: "재인국어학원-디퍼즈",
    col: "본안소송",
    labels: ["lb12"],
    drv: "https://drive.google.com",
    lu: da(35),
    tl: [{ dt: "2025.10.01", ti: "분쟁 접수", dn: true }],
    fu: [],
  },
  {
    id: "d4",
    name: "설문조사 웹 MVP",
    sub: "정석필름-팀에브리웨어",
    col: "본안소송",
    labels: ["lb13"],
    drv: "https://drive.google.com",
    lu: da(8),
    tl: [{ dt: "2025.07.01", ti: "분쟁 접수", dn: true }],
    fu: [],
  },
  {
    id: "d5",
    name: "포토 키오스크 SW",
    sub: "정유경-디엑스플레이그라운드",
    col: "법무이관",
    labels: ["lb14"],
    drv: "https://drive.google.com",
    lu: da(14),
    tl: [{ dt: "2026.03.13", ti: "법무이관", dn: true }],
    fu: [],
  },
  {
    id: "d6",
    name: "정재훈 위약벌 청구",
    sub: "일방적 계약 파탄",
    col: "강제집행",
    labels: ["lb15"],
    drv: "https://drive.google.com",
    lu: da(5),
    tl: [{ dt: "2025.11.01", ti: "분쟁 접수", dn: true }],
    fu: [],
  },
  {
    id: "d7",
    name: "플래어 영업비밀",
    sub: "영업비밀 침해 사건",
    col: "종결",
    labels: ["lb16"],
    drv: "https://drive.google.com",
    lu: da(20),
    tl: [{ dt: "2025.12.05", ti: "종결", dc: "합의 완료", dn: true }],
    fu: [],
  },
];
